### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [13]:
import random
import numpy as np

vector = np.random.rand(1, 10)
display(vector)
#v2 = np.array([[random.uniform(0, 1) for el in range(10)]])

matrix = np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]])
display(matrix)

array([[0.52307819, 0.15672123, 0.23938746, 0.7663744 , 0.99401227,
        0.15868627, 0.58665881, 0.5600114 , 0.30354141, 0.92646988]])

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [19]:
vector_1 = (vector + 10).round(2)
display(vector_1)

matrix_1 = matrix * 2
display(matrix_1)



array([[10.52, 10.16, 10.24, 10.77, 10.99, 10.16, 10.59, 10.56, 10.3 ,
        10.93]])

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [20]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [22]:
result_matrix = np.dot(B, A)
display(result_matrix)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [25]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [27]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [29]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [35]:
display(vector)
vector.shape

array([[0.52307819, 0.15672123, 0.23938746, 0.7663744 , 0.99401227,
        0.15868627, 0.58665881, 0.5600114 , 0.30354141, 0.92646988]])

(1, 10)

In [34]:
vector_T = vector.T
display(vector_T)
display(vector_T.shape)

# був вектор-рядок, став вектор-стовпець

array([[0.52307819],
       [0.15672123],
       [0.23938746],
       [0.7663744 ],
       [0.99401227],
       [0.15868627],
       [0.58665881],
       [0.5600114 ],
       [0.30354141],
       [0.92646988]])

(10, 1)

In [37]:
column_vector = np.expand_dims(vector, axis=1)
display(column_vector)
display(column_vector.shape)

# vector 2 вимірний, column_vector - 3 вимірний

array([[[0.52307819, 0.15672123, 0.23938746, 0.7663744 , 0.99401227,
         0.15868627, 0.58665881, 0.5600114 , 0.30354141, 0.92646988]]])

(1, 1, 10)

In [38]:
column_vector_T = column_vector.T
display(column_vector_T)

array([[[0.52307819]],

       [[0.15672123]],

       [[0.23938746]],

       [[0.7663744 ]],

       [[0.99401227]],

       [[0.15868627]],

       [[0.58665881]],

       [[0.5600114 ]],

       [[0.30354141]],

       [[0.92646988]]])

In [39]:
display(column_vector_T.shape)

(10, 1, 1)